name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npx enhanced-publish --if-possible --use-preid-as-tag --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
